### PR TITLE
refactor code relying on ActiveStorage::Service private method path_for

### PR DESCRIPTION
**Pull request by wschaefer-cfa**
[#160521773]

### CODE REVIEW

**Comment by hartsick** [comment]
@wschaefer-cfa Hi! Trying to understand this a bit better—is there a danger that the temp file we're writing to disappears before we need it?

**Comment by wschaefer-cfa** [comment]
@hartsick I'm just trying some stuff since things that work fine locally aren't working on heroku - i should have marked this as a wip.

I'm not totally sure, but I actually think since it's not using ruby Tempfile the bigger risk is that they won't get cleaned up if we don't clean them up ourselves. If it actually works on heroku, i will investigate further.

**Comment by hartsick** [comment]
@wschaefer-cfa gotcha! sorry didn't mean to swoop in, didn't realize it was a wip

**Comment by wschaefer-cfa** [comment]
@hartsick no worries! it was my bad for not marking it. I read up on the ephemeral filesystem and it looks like the file storage will be adequate for our usage (we only need the file to stick around for the duration of a single request) - https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

**Pull request merged**
