### PR TITLE
Feature/sign change report

### PR DESCRIPTION
**Pull request by hartsick**
Does a couple of things!

* Adds 'Sign and submit' page at end of flow
* Throws helpful error if master.key file is missing in development or production environments (useful for setting up your dev environment)
* Adds simple generator for section pages (e.g. `rails g section SignSubmit`) based off of MichiganBenefits generator — to try it out and see what it'll generate, run `rails g section --help`)
* Requires current change report by default, and skips the related before action in existing pages where we don't require a current change report

screen shot 2018-09-17 at 6 16 22 pm

### CODE REVIEW

**Comment by wschaefer-cfa** [comment]
I like `screen`

**Comment by hartsick** [comment]
@luigi do you mean just for the generator, or also for the URLs? I think exposing that to clients (e.g. '/screens/sign-submit') seems a little technical though I agree sections isn't totally accurate, either!

**Comment by luigi** [comment]
Yeah, I meant both.

**Comment by hartsick** [comment]
sure sounds good to me! I'm going to merge this PR (trying to get things onto master before my flight, so we have a consistent base) and do it in a separate commit / branch.

**Pull request merged**
